package otus.gpb.recyclerview

object Generator {

    fun generate(): MutableList<Chat> {
        return mutableListOf(
            Chat(
                id = 1L,
                title = "SnejUgal News",
                isTitle = true,
                author =  "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent =  true,
                isMail =  false,
                isFix = false,
                isOK = true,
                time =  "11:38",
            ),
            Chat(
                id = 2L,
                title = "SnejUgal News2",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  false,
                isMail =  false,
                isFix = false,
                time =  "11:39",
            ),
            Chat(
                id = 3L,
                title = "SnejUgal News3",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  true,
                isMail =  true,
                isFix = true,
                time =  "11:40",
            ),
            Chat(
                id = 4L,
                title = "SnejUgal News4",
                isTitle = true,
                author =  "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent =  true,
                isMail =  false,
                isFix = false,
                isOK = true,
                time =  "11:38",
            ),
            Chat(
                id = 5L,
                title = "SnejUgal News5",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  false,
                isMail =  false,
                isFix = false,
                time =  "11:39",
            ),
            Chat(
                id = 6L,
                title = "SnejUgal News6",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  true,
                isMail =  true,
                isFix = true,
                time =  "11:40",
            ),
            Chat(
                id = 7L,
                title = "SnejUgal News7",
                isTitle = true,
                author =  "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent =  true,
                isMail =  false,
                isFix = false,
                isOK = true,
                time =  "11:38",
            ),
            Chat(
                id = 8L,
                title = "SnejUgal News8",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  false,
                isMail =  false,
                isFix = false,
                time =  "11:39",
            ),
            Chat(
                id = 9L,
                title = "SnejUgal News9",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  true,
                isMail =  true,
                isFix = true,
                time =  "11:40",
            ),
            Chat(
                id = 10L,
                title = "SnejUgal News10",
                author =  "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent =  true,
                isMail =  true,
                isFix = true,
                time =  "11:40",
            ),
        )
    }
}