package otus.gpb.recyclerview

object Generator {

    fun generate(): MutableList<Chat> {
        return mutableListOf(
            Chat(
                id = 1L,
                title = "SnejUgal News",
                isTitle = false,
                author = "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent = true,
                isMail = false,
                isFix = false,
                isOK = false,
                time = "11:38 AM",
            ),
            Chat(
                id = 2L,
                title = "SnejUgal News2",
                isTitle = true,
                imgAuthor = "https://fototips.ru/wp-content/uploads/2016/10/pounce_07.jpg",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = false,
                isMail = true,
                isFix = false,
                time = "11:39 AM",
            ),
            Chat(
                id = 3L,
                title = "SnejUgal News3",
                author = "Dima Murantsev",
                imgAuthor = "https://10wallpaper.com/wallpaper/1680x1050/1107/Cat_wallpaper_1680x1050.jpg",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "11:40 AM",
            ),
            Chat(
                id = 4L,
                title = "SnejUgal News4",
                isTitle = true,
                imgAuthor = "https://lirider.ru/pictures/product/middle/23007_middle.jpg",
                author = "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent = true,
                isMail = false,
                isFix = false,
                isOK = true,
                time = "11:38 AM",
            ),
            Chat(
                id = 5L,
                title = "SnejUgal News5",
                author = "Dima Murantsev",
                imgAuthor = "https://sun6-21.userapi.com/s/v1/if1/WjDe4y6aSUP4GQoRPDjsmi5Tmnrjpu2jtD5cX_gCY8g0FEArbP7BAtmKdGBDNx6M1w78Kg.jpg?size=1429x1431&quality=96&crop=347,106,1429,1431&ava=1",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = false,
                isMail = false,
                isFix = false,
                time = "11:39 AM",
            ),
            Chat(
                id = 6L,
                title = "SnejUgal News6",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "11:40 AM",
            ),
            Chat(
                id = 7L,
                title = "SnejUgal News7",
                isTitle = true,
                imgAuthor = "https://get.pxhere.com/photo/grass-sweet-animal-cute-fur-orange-young-kitten-cat-small-feline-mammal-yellow-whisker-fauna-playful-shelter-whiskers-paw-furry-vertebrate-funny-adorable-cute-cat-adopt-rescue-maine-coon-red-cat-tabby-kitten-ginger-kitten-small-to-medium-sized-cats-cat-like-mammal-carnivoran-576766.jpg",
                author = "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent = true,
                isMail = false,
                isFix = false,
                isOK = true,
                time = "11:38 AM",
            ),
            Chat(
                id = 8L,
                title = "SnejUgal News8",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = false,
                isMail = false,
                isFix = false,
                time = "11:39",
            ),
            Chat(
                id = 9L,
                title = "SnejUgal News9",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "11:40 AM ",
            ),
            Chat(
                id = 10L,
                title = "SnejUgal News10",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "Fri",
            ),
        )
    }

    fun generate2(): MutableList<Chat> {
        return mutableListOf(
            Chat(
                id = 100L,
                title = "SnejUgal News100",
                isTitle = false,
                author = "Nikolay",
                message = "I want pizza",
                avatar = "",
                isSilent = true,
                isMail = false,
                isFix = false,
                isOK = false,
                time = "11:38 AM",
            ),
            Chat(
                id = 109L,
                title = "SnejUgal News109",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "11:40 AM ",
            ),
            Chat(
                id = 110L,
                title = "SnejUgal News110",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "Fri",
            ),
            Chat(
                id = 111L,
                title = "SnejUgal News111",
                author = "Dima Murantsev",
                message = "you are welcome :)",
                avatar = "@tools:sample/avatars",
                isSilent = true,
                isMail = true,
                isFix = true,
                time = "Fri",
            ),
        )
    }
}